
[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/themes/nord.toml" ]
# import = [ "~/.config/alacritty/themes/themes/nord_light.toml" ]
[env]
TERM = "xterm-256color"
Where = "alacritty" #用作代表终端模拟器是alacritty

[window]
dynamic_title = true
decorations ="Buttonless" #"Transparent"
opacity = 1.0
startup_mode = "Maximized"
option_as_alt = "Both"
blur=true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

[font.offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"


[ bell ] #echo -e `\a`  触发响铃
animation = "EaseOutExpo"
duration = 200   # >0开启闪屏，毫秒
color = "#42a5f5"
command = "None"

# [ selection ]
# save_to_clipboard = true


[cursor]
blink_interval = 500
thickness = 0.15 #光标的宽度

[cursor.style]
shape = "Beam"
blinking="Always" #闪烁

[terminal.shell]
program = "/opt/homebrew/bin/zellij"
args = ["attach", "-c", "default" ]

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ReceiveChar"


[[keyboard.bindings]]
key = ";"
mods = "Command"
action = "ToggleViMode"
mode = "~Alt"

# \u001b = ESC
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

# [[ keyboard.bindings]]
# key = "F"
# mods = "Control|Shift"
# action = "CreateNewWindow"

# [[ keyboard.bindings]]
# key = "F"
# mods = "Command|Shift"
# chars = "\u001b[29~"



# [[ keyboard.bindings]]
# key = "F"
# mods = "Control"
# chars = "\u001b[29~"


# [[keyboard.bindings]]
# key = "S"
# mods = "Command"
# chars = "\u001b:silent w!\r"

# f14 桥接不需要了,不是黑苹果,白苹果neovim原生支持<d-s>
# [[keyboard.bindings]]
# key = "S"
# mods = "Command"
# chars = "\u001b[26~"


[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "ReceiveChar"

# 默认的行为会退出
[[keyboard.bindings]]
key = "q"
mods = "Control"
chars = "None"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
chars = "\u001b[28~"


[[keyboard.bindings]] #需要保留这个，arch的super+c = control+insert = 5~
key = "Insert"
mods = "Control"
action = "copy"

# [[keyboard.bindings]]
# key = "T"
# mods = "Command"
# chars = "\u001b[25~"


[terminal]
# chars = "\u001b[1;2Q" #esc+f14


#ANSI 转义 chars的内容 [:转义开始 ~:转义结束
#需要与\u001b配合使用
# 功能键	ANSI 转义序列
# F1	\u001b[11~
# F2	\u001b[12~
# F3	\u001b[13~
# F4	\u001b[14~
# F5	\u001b[15~
# F6	\u001b[17~
# F7	\u001b[18~
# F8	\u001b[19~
# F9	\u001b[20~
# F10	\u001b[21~
# F11	\u001b[23~
# F12	\u001b[24~
# F13	\u001b[25~
# F14	\u001b[26~
# F15	\u001b[28~
# F16	\u001b[29~
# F17	\u001b[31~
# F18	\u001b[32~
# F19	\u001b[33~
# F20	\u001b[34~
# F21	\u001b[35~
# F22	\u001b[36~
# F23	\u001b[37~
# F24	\u001b[38~
# F25	\u001b[50~
# F26	\u001b[51~
# F27	\u001b[52~
# F28	\u001b[53~
# F29	\u001b[54~
# F30	\u001b[55~

