import = [ "~/.config/alacritty/themes/themes/nord.toml" ]
live_config_reload = true

[window]
dynamic_title = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 15

  [font.normal]
  family = "MesloLGS NF"
  style = "Regular"

  [font.bold]
  family = "MesloLGS NF"
  style = "Bold"

  [font.italic]
  family = "MesloLGS NF"
  style = "Italic"

  [font.bold_italic]
  family = "MesloLGS NF"
  style = "Bold Italic"

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Block"

[shell]
program = "/bin/zsh"
args = [ "--login" ]

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u001b:w\r"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
chars = "\u001b:NvimTreeFindFile\r"

[[keyboard.bindings]]
key = "A"
mods = "Option"
chars = "\u001ba"

[[keyboard.bindings]]
key = "B"
mods = "Option"
chars = "\u001bb"

[[keyboard.bindings]]
key = "C"
mods = "Option"
chars = "\u001bc"

[[keyboard.bindings]]
key = "D"
mods = "Option"
chars = "\u001bd"

[[keyboard.bindings]]
key = "E"
mods = "Option"
chars = "\u001be"

[[keyboard.bindings]]
key = "F"
mods = "Option"
chars = "\u001bf"

[[keyboard.bindings]]
key = "G"
mods = "Option"
chars = "\u001bg"

[[keyboard.bindings]]
key = "H"
mods = "Option"
chars = "\u001bh"

[[keyboard.bindings]]
key = "I"
mods = "Option"
chars = "\u001bi"

[[keyboard.bindings]]
key = "J"
mods = "Option"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Option"
chars = "\u001bk"

[[keyboard.bindings]]
key = "L"
mods = "Option"
chars = "\u001bl"

[[keyboard.bindings]]
key = "M"
mods = "Option"
chars = "\u001bm"

[[keyboard.bindings]]
key = "N"
mods = "Option"
chars = "\u001bn"

[[keyboard.bindings]]
key = "O"
mods = "Option"
chars = "\u001bo"

[[keyboard.bindings]]
key = "P"
mods = "Option"
chars = "\u001bp"

[[keyboard.bindings]]
key = "Q"
mods = "Option"
chars = "\u001bq"

[[keyboard.bindings]]
key = "R"
mods = "Option"
chars = "\u001br"

[[keyboard.bindings]]
key = "S"
mods = "Option"
chars = "\u001bs"

[[keyboard.bindings]]
key = "T"
mods = "Option"
chars = "\u001bt"

[[keyboard.bindings]]
key = "U"
mods = "Option"
chars = "\u001bu"

[[keyboard.bindings]]
key = "V"
mods = "Option"
chars = "\u001bv"

[[keyboard.bindings]]
key = "W"
mods = "Option"
chars = "\u001bw"

[[keyboard.bindings]]
key = "X"
mods = "Option"
chars = "\u001bx"

[[keyboard.bindings]]
key = "Y"
mods = "Option"
chars = "\u001by"

[[keyboard.bindings]]
key = "Z"
mods = "Option"
chars = "\u001bz"

[[keyboard.bindings]]
key = "A"
mods = "Option|Shift"
chars = "\u001bA"

[[keyboard.bindings]]
key = "B"
mods = "Option|Shift"
chars = "\u001bB"

[[keyboard.bindings]]
key = "C"
mods = "Option|Shift"
chars = "\u001bC"

[[keyboard.bindings]]
key = "D"
mods = "Option|Shift"
chars = "\u001bD"

[[keyboard.bindings]]
key = "E"
mods = "Option|Shift"
chars = "\u001bE"

[[keyboard.bindings]]
key = "F"
mods = "Option|Shift"
chars = "\u001bF"

[[keyboard.bindings]]
key = "G"
mods = "Option|Shift"
chars = "\u001bG"

[[keyboard.bindings]]
key = "H"
mods = "Option|Shift"
chars = "\u001bH"

[[keyboard.bindings]]
key = "I"
mods = "Option|Shift"
chars = "\u001bI"

[[keyboard.bindings]]
key = "J"
mods = "Option|Shift"
chars = "\u001bJ"

[[keyboard.bindings]]
key = "K"
mods = "Option|Shift"
chars = "\u001bK"

[[keyboard.bindings]]
key = "L"
mods = "Option|Shift"
chars = "\u001bL"

[[keyboard.bindings]]
key = "M"
mods = "Option|Shift"
chars = "\u001bM"

[[keyboard.bindings]]
key = "N"
mods = "Option|Shift"
chars = "\u001bN"

[[keyboard.bindings]]
key = "O"
mods = "Option|Shift"
chars = "\u001bO"

[[keyboard.bindings]]
key = "P"
mods = "Option|Shift"
chars = "\u001bP"

[[keyboard.bindings]]
key = "Q"
mods = "Option|Shift"
chars = "\u001bQ"

[[keyboard.bindings]]
key = "R"
mods = "Option|Shift"
chars = "\u001bR"

[[keyboard.bindings]]
key = "S"
mods = "Option|Shift"
chars = "\u001bS"

[[keyboard.bindings]]
key = "T"
mods = "Option|Shift"
chars = "\u001bT"

[[keyboard.bindings]]
key = "U"
mods = "Option|Shift"
chars = "\u001bU"

[[keyboard.bindings]]
key = "V"
mods = "Option|Shift"
chars = "\u001bV"

[[keyboard.bindings]]
key = "W"
mods = "Option|Shift"
chars = "\u001bW"

[[keyboard.bindings]]
key = "X"
mods = "Option|Shift"
chars = "\u001bX"

[[keyboard.bindings]]
key = "Y"
mods = "Option|Shift"
chars = "\u001bY"

[[keyboard.bindings]]
key = "Z"
mods = "Option|Shift"
chars = "\u001bZ"

[[keyboard.bindings]]
key = "Key0"
mods = "Option"
chars = "\u001b0"

[[keyboard.bindings]]
key = "Key1"
mods = "Option"
chars = "\u001b1"

[[keyboard.bindings]]
key = "Key2"
mods = "Option"
chars = "\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Option"
chars = "\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Option"
chars = "\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Option"
chars = "\u001b5"

[[keyboard.bindings]]
key = "Key6"
mods = "Option"
chars = "\u001b6"

[[keyboard.bindings]]
key = "Key7"
mods = "Option"
chars = "\u001b7"

[[keyboard.bindings]]
key = "Key8"
mods = "Option"
chars = "\u001b8"

[[keyboard.bindings]]
key = "Key9"
mods = "Option"
chars = "\u001b9"

# [[keyboard.bindings]]
# key = "Grave"
# mods = "Option"
# chars = "\u001b`"

[[keyboard.bindings]]
key = "Minus"
mods = "Option"
chars = "\u001b-"

[[keyboard.bindings]]
key = "Equals"
mods = "Option"
chars = "\u001b="

[[keyboard.bindings]]
key = "LBracket"
mods = "Option"
chars = "\u001b["

[[keyboard.bindings]]
key = "RBracket"
mods = "Option"
chars = "\u001b]"

[[keyboard.bindings]]
key = "Backslash"
mods = "Option"
chars = "\u001b\\"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Option"
chars = "\u001b;"

# [[keyboard.bindings]]
# key = "Apostrophe"
# mods = "Option"
# chars = "\u001b'"

[[keyboard.bindings]]
key = "Comma"
mods = "Option"
chars = "\u001b,"

[[keyboard.bindings]]
key = "Period"
mods = "Option"
chars = "\u001b."

[[keyboard.bindings]]
key = "Slash"
mods = "Option"
chars = "\u001b/"

# [[keyboard.bindings]]
# key = "Grave"
# mods = "Option|Shift"
# chars = "\u001b~"

[[keyboard.bindings]]
key = "Key1"
mods = "Option|Shift"
chars = "\u001b!"

[[keyboard.bindings]]
key = "Key2"
mods = "Option|Shift"
chars = "\u001b@"

[[keyboard.bindings]]
key = "Key3"
mods = "Option|Shift"
chars = "\u001b#"

[[keyboard.bindings]]
key = "Key4"
mods = "Option|Shift"
chars = "\u001b$"

[[keyboard.bindings]]
key = "Key5"
mods = "Option|Shift"
chars = "\u001b%"

[[keyboard.bindings]]
key = "Key6"
mods = "Option|Shift"
chars = "\u001b^"

[[keyboard.bindings]]
key = "Key7"
mods = "Option|Shift"
chars = "\u001b&"

[[keyboard.bindings]]
key = "Key8"
mods = "Option|Shift"
chars = "\u001b*"

[[keyboard.bindings]]
key = "Key9"
mods = "Option|Shift"
chars = "\u001b("

[[keyboard.bindings]]
key = "Key0"
mods = "Option|Shift"
chars = "\u001b)"

[[keyboard.bindings]]
key = "Minus"
mods = "Option|Shift"
chars = "\u001b_"

[[keyboard.bindings]]
key = "Equals"
mods = "Option|Shift"
chars = "\u001b+"

[[keyboard.bindings]]
key = "LBracket"
mods = "Option|Shift"
chars = "\u001b{"

[[keyboard.bindings]]
key = "RBracket"
mods = "Option|Shift"
chars = "\u001b}"

[[keyboard.bindings]]
key = "Backslash"
mods = "Option|Shift"
chars = "\u001b|"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Option|Shift"
chars = "\u001b:"

# [[keyboard.bindings]]
# key = "Apostrophe"
# mods = "Option|Shift"
# chars = '"'

[[keyboard.bindings]]
key = "Comma"
mods = "Option|Shift"
chars = "\u001b<"

[[keyboard.bindings]]
key = "Period"
mods = "Option|Shift"
chars = "\u001b>"

[[keyboard.bindings]]
key = "Slash"
mods = "Option|Shift"
chars = "\u001b?"

