import = [ "~/.config/alacritty/themes/themes/nord.toml" ]
live_config_reload = true

[window]
dynamic_title = true
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
blur=true

[font]
size = 16

[font.offset]
x = 0
y = 1

[font.normal]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
# family = "MesloLGS NF"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Beam"

[shell]
program = "/bin/zsh"
args = [ "--login" ,"-c", "zellij attach -c default" ]

# \u001b = ESC
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"


[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u001b:silent w\r"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
chars = "\u001b:NvimTreeFindFile\r"

[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b:OutlineFocus\r"

[[keyboard.bindings]]
key = "."
mods = "Control"
chars = "\u001b:OutlineFocus\r"

#ANSI 转义 chars的内容 [:转义开始 ~:转义结束
#需要与\u001b配合使用
# 功能键	ANSI 转义序列
# F1	[11~
# F2	[12~
# F3	[13~
# F4	[14~
# F5	[15~
# F6	[17~
# F7	[18~
# F8	[19~
# F9	[20~
# F10	[21~
# F11	[23~
# F12	[24~
# F13	[25~
# F14	[26~
# F15	[28~
# F16	[29~
# F17	[31~
# F18	[32~
# F19	[33~
# F20	[34~
# F21	[35~
# F22	[36~
# F23	[23~
# F24	[24~
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u001b[25~"
# chars = "\u001b[1;2Q" #esc+f14


