import = [ "~/.config/alacritty/themes/themes/nord.toml" ]
live_config_reload = true

[window]
dynamic_title = true
decorations = "Transparent"
startup_mode = "Maximized"
option_as_alt = "Both"
blur=true

[font]
size = 16

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Block"

[shell]
program = "/bin/zsh"
args = [ "--login" ,"-c", "zellij attach -c default" ]

# \u001b = ESC
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"


[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u001b:w\r"

[[keyboard.bindings]]
key = "H"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
chars = "\u001b:NvimTreeFindFile\r"

[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b:OutlineFocus\r"

[[keyboard.bindings]]
key = "."
mods = "Control"
chars = "\u001b:OutlineFocus\r"


[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u001b:ToggleTerm size=40 direction=horizontal\r"


