# keybind = ctrl+d=text:\x15
# ignore start ================================
keybind = super+alt+arrow_down=ignore
keybind = super+alt+arrow_left=ignore
keybind = super+alt+arrow_right=ignore
keybind = super+alt+arrow_up=ignore
keybind = super+ctrl+arrow_down=ignore
keybind = super+ctrl+arrow_left=ignore
keybind = super+ctrl+arrow_right=ignore
keybind = super+ctrl+arrow_up=ignore
keybind = super+ctrl+equal=ignore
keybind = super+shift+enter=ignore
keybind = ctrl+k=unbind
#再zellij里面用来指定尺寸的，所有注释掉
keybind = alt+arrow_down=unbind
keybind = alt+arrow_left=unbind
keybind = alt+arrow_right=unbind
keybind = alt+arrow_up=unbind
# ignore end ================================

# super + alt   + arrow_down      goto_split:down
# super + alt   + arrow_left      goto_split:left
# super + alt   + arrow_right     goto_split:right
# super + alt   + arrow_up        goto_split:up

keybind = super+h=goto_split:left
keybind = super+j=goto_split:down
keybind = super+k=goto_split:up
keybind = super+l=goto_split:right
# keybind = super+ctrl+k=clear_screen
keybind = super+shift+semicolon=move_tab:-1
keybind = super+shift+quote=move_tab:1
keybind = super+shift+x=close_tab
keybind = super+shift+equal=equalize_splits
keybind = super+arrow_down=resize_split:down,10
keybind = super+arrow_left=resize_split:left,10
keybind = super+arrow_right=resize_split:right,10
keybind = super+arrow_up=resize_split:up,10
keybind = super+enter=toggle_split_zoom
