export HOMEBREW_NO_AUTO_UPDATE=1
#PATH start
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export GO111MODULE=on
export GOPROXY="https://goproxy.cn"
export PATH=$PATH:$GOBIN
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$PATH:/usr/local/mysql/bin"
export DENO_INSTALL="/Users/mac/.deno"
export PNPM_HOME="$HOME/.pnpm"
export PATH="$PNPM_HOME:$PATH"
export PATH="$PATH:$HOME/Library/Android/sdk/build-tools/30.0.3"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools:/usr/local/bin"
export PATH=$PATH:/opt/homebrew/bin
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/share/nvim/mason/bin:$PATH

#PATH end
# 插件目录 .local/share/zsh/plugins
# 插件开始
PLUGINS_PATH=$HOME/.local/share/zsh/plugins
[ -e $HOME/.config/zsh/zsh_tool.sh ] && source $HOME/.config/zsh/zsh_tool.sh
#git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${PLUGINS_PATH}/powerlevel10k
source ${PLUGINS_PATH}/powerlevel10k/powerlevel10k.zsh-theme
#git clone https://github.com/zsh-users/zsh-autosuggestions ${PLUGINS_PATH}/zsh-autosuggestions
source ${PLUGINS_PATH}/zsh-autosuggestions/zsh-autosuggestions.zsh
# do this in terminal when fzf-tab not working
autoload -U compinit
compinit
#git clone https://github.com/Aloxaf/fzf-tab ${PLUGINS_PATH}/fzf-tab
source ${PLUGINS_PATH}/fzf-tab/fzf-tab.plugin.zsh
source $HOME/.config/zsh/fzf-tab.sh # 针对fzf-tab一些独立的配置
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

#git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ${PLUGINS_PATH}/fast-syntax-highlighting
source ${PLUGINS_PATH}/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh #命令高亮
# brew install autojump 这个插件不需要注入到这个文件里
# 插件end

export LC_ALL=en_US.UTF-8

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home

function fg() {
    if [[ $# -eq 1 && $1 = - ]]; then
        builtin fg %-
    else
        builtin fg %"$@"
    fi
}

export EDITOR=nvim #yazi打开的默认编辑器
function f() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}
# alias start
alias e=nvim
alias vi=nvim
alias vim=vim
alias neococos="nvim --listen 127.0.0.1:6553"
# alias ls="ls --color=auto"
alias r="source $HOME/.zshrc"
alias d="kitty +kitten diff"
alias w="cd ~/go/workSpace"
alias c="cd ~/.config"
alias g="gitui"
# alias end
# 命令替换start
# https://github.com/sigoden/aichat #ai工具
eval "$(zoxide init zsh)"
alias cd="z" #z is zoxide
alias ls="lsd"
alias ll="ls -lah"
alias du="dust"
alias top="btm" #brew install bottom
alias cat="bat --color never"
alias grep="rg"
alias diff="delta"
alias merge="meld"
# alias sed="sd"
alias df="duf"
alias t="tldr" #brew install tealdeer #命令的常用语法
alias ps="procs"
alias find="fd"
alias s="spf"
# 命令替换end

export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
fd1() {
    local dir
    dir=$(find ${1:-.} -path '*/\.*' -prune \
        -o -type d -print 2>/dev/null | fzf +m) &&
        cd "$dir"
}

# kitty start
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
alias ts=ts-node
alias tr="ts-node-dev  -r tsconfig-paths/register  --respawn --transpile-only" #tsconfig-paths/register 是为了解决tsconfig-paths的问题
alias pn="pnpm"
alias ssh="TERM=xterm-256color ssh"
# kitty end
#

export FZF_DEFAULT_COMMAND="fd --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build,dist,vendor} --type f"
export FZF_DEFAULT_OPTS='--color=bg+:#3c3836,bg:#32302f,spinner:#fb4934,hl:#928374,fg:#ebdbb2,header:#928374,info:#8ec07c,pointer:#fb4934,marker:#fb4934,fg+:#ebdbb2,prompt:#fb4934,hl+:#fb4934'

export TZ='Asia/Bangkok'

alias ts="ts-node-dev --respawn "
if [[ -e $HOME/.zshrc_local ]]; then
    source $HOME/.zshrc_local
fi

# zellij start
# 自动启动zellij ,已经在各个终端配置好了，不需要再这里启动了
# eval "$(zellij setup --generate-auto-start zsh)"
#
#打开默认
function zz() {
    zellij attach -c default
}

#会话列表
function zl() {
    zellij list-sessions
}

#指定名字创建一个会话
function zc() {
    session_name=$1
    if [ -z ${session_name} ]; then
        echo "必须指定一个会话名字"
        return
    fi
    zellij attach -c ${session_name}
}

#链接一个现有的会话,大于2个选择，只有一个默认打开，一个都没有就打开default
function za() {
    zellij da -y
    ZJ_SESSIONS=$(zellij list-sessions | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g")
    NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)
    if [ "${NO_SESSIONS}" -ge 2 ]; then
        zellij attach \
            "$(echo "${ZJ_SESSIONS}" | sk | awk '{print $1}')"
    elif [ "${NO_SESSIONS}" -eq 1 ]; then
        zellij attach -c
    else
        zellij attach -c default
    fi
}
# zellij end
export useryy=12 #这是一个标识，表示只在本机

# set -o emacs 与bindkey -e 等价的，二选一即可，都是为了使用emacs模式，就是说常用的ctrl+a,e之类的快捷键
bindkey -e

# neofetch
# brew install fastfetch
fastfetch

function proxy_on() {
    local port=7890
    if [ $# -eq 1 ]; then
        port=$1
    fi
    export all_proxy=socks5://0.0.0.0:$port
}

function proxy_http_on() {
    local port=7890
    if [ $# -eq 1 ]; then
        port=$1
    fi
    export http_proxy=http://127.0.0.1:$port
    export https_proxy=http://127.0.0.1:$port
}

function proxy_all_on() {
    local port=7890
    if [ $# -eq 1 ]; then
        port=$1
    fi
    export http_proxy=http://127.0.0.1:$port
    export https_proxy=http://127.0.0.1:$port
    export all_proxy=socks5://127.0.0.1:$port
}

function proxy_off() {
    unset http_proxy
    unset https_proxy
    unset all_proxy
}

function ip() {
    curl ipinfo.io
}

function wk() {
    ssh wk
}
