export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source $HOME/.local/share/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
plugins=(git)
source $ZSH/oh-my-zsh.sh
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/go/bin
echo "天空一声巨响，老子闪亮登场"
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
GOPATH="$HOME/go"
GOPRIVATE="local.weiyou.com"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="$PATH:/usr/local/mysql/bin"
export GO111MODULE=on
export GOPROXY="https://goproxy.cn"
export LC_ALL=en_US.UTF-8
alias goenv="docker exec -it goenv /bin/zsh"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home
alias vi nvim
alias vim nvim
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
function proxy(){
  nohup shadowsocks2-macos -c 'ss://AEAD_CHACHA20_POLY1305:hZYOgw61z41mb4q1@[tg-hy-test]:8678' \
        -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 \
                                     -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 &
  # nohup ssh -Nfg -D 127.0.0.1:1080 root@tg-uf-test > proxy.log 2>&1 &
}

function unproxy(){
 if  pkill shadowsocks2-macos;then
   proxy_off
 fi
}

function proxy_off(){
  unset all_proxy
  echo "************ 关闭当前终端代理 **********"
}

function proxy_on(){
  export all_proxy=socks5://127.0.0.1:1080
  echo "************ 开启当前终端代理 **********"
 if ! curl cip.cc ;then
   echo "************开启socket5***************"
   proxy
   curl cip.cc
 fi
}
if [ -z $KITTY_PID ];then
# proxy_on
fi




function fg(){
  if [[ $# -eq 1 && $1 = - ]];then
    builtin fg %-
  else
    builtin fg %"$@"
  fi
}
function ip(){
  curl cip.cc
  #curl http://pv.sohu.com/cityjson
}
alias d="kitty +kitten diff"
alias w="cd ~/go/workSpace"
alias c="cd ~/.config"
alias g="guiui"
alias uf="cd ~/go/workSpace/jinguf && nvim" 
alias hy="cd ~/go/workSpace/jinghy && nvim" 


function lg()
{
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

    lazygit "$@"

    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
            cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
            rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}

#function ssh() {
    #c=$(curl -s cip.cc | grep 成都 | wc -l)
    #if [ $c -gt 0 ];then
        #echo "请先开启代理"
        #return
    #fi
     #/usr/bin/ssh $1
#}

LC_ALL=zh_CN.UTF-8
HOMEBREW_BOTTLE_DOMAIN=
export PATH="$PATH:$HOME/Library/Android/sdk/build-tools/30.0.3"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools:/usr/local/bin"
export FZF_DEFAULT_COMMAND="fd --exclude={.git,.idea,.sass-cache,node_modules,build} --type f"
fd1() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
				  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
export DENO_INSTALL="/Users/mac/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
alias dot=dotnet

# pnpm
export PNPM_HOME="/Users/mac/Library/pnpm"
export PATH="$PATH:/Users/mac/.dotnet/tools"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
# kitty start
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
alias ts=ts-node
# kitty end

export FZF_DEFAULT_OPTS='--color=bg+:#3c3836,bg:#32302f,spinner:#fb4934,hl:#928374,fg:#ebdbb2,header:#928374,info:#8ec07c,pointer:#fb4934,marker:#fb4934,fg+:#ebdbb2,prompt:#fb4934,hl+:#fb4934'

export TZ='Asia/Bangkok'

alias ts="ts-node-dev --respawn "
if [[ -e ./.zshrc_local ]]; then
  source ./.zshrc_local
fi

